In [1]:
import pandas as pd
import plotnine as p9
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
#Reading .csv files
t06 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2006.csv")
t07 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2007.csv")
t09 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2009.csv")
t10 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2010.csv")
t11 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2011.csv")
t12 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2012.csv")
t13 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2013.csv")
t14 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2014.csv")
t15 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2015.csv")
t16 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2016.csv")
t17 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2017.csv")
t18 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2018.csv")
t19 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2019.csv")
t20 = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\2020.csv")
h_recycle = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\household-recycling-borough.csv")
income = pd.read_csv(r"C:\Users\samur\Desktop\LIS Term 2\quant1b_group_summative\income-of-tax-payers.csv")

In [3]:
#checking the format
t07.head()

                Borough  Own Outright  Buying with mortgage
0  Barking and Dagenham          21.5                  34.3
1                Barnet          30.1                  36.8
2                Bexley          32.6                  45.3
3                 Brent          23.9                  30.2
4               Bromley          31.6                  42.9

In [4]:
#making a list of the all the dataframes to concat them all together
df_list= []
df_list.append(t06)
df_list.append(t07)
df_list.append(t09)
df_list.append(t10)
df_list.append(t11)
df_list.append(t12)
df_list.append(t13)
df_list.append(t14)
df_list.append(t15)
df_list.append(t16)
df_list.append(t17)
df_list.append(t18)
df_list.append(t19)
df_list.append(t20)

#add a year column to tenure df's 
count = 0
for i in df_list:
    count = count + 1
    if count == 1:
        i["Year"] = 2006
    elif count ==2:
        i["Year"] = 2007
    else:
        i["Year"] = 2006 + count


for i in df_list:
    #renaming "Borough" column to "Area"
    i.rename(columns={"Borough":"Area"}, inplace=True)

    #getting rid of "inner london", "outer london" and "london" rows
    i.drop([32,33,34], axis=0, inplace=True)   

#concatanating tenure dataframes
tenure = pd.concat(df_list, ignore_index=True)

tenure.head()

                   Area  Own Outright  Buying with mortgage  Year
0  Barking and Dagenham          21.6                  32.4  2006
1                Barnet          27.7                  35.0  2006
2                Bexley          28.5                  47.2  2006
3                 Brent          21.3                  32.3  2006
4               Bromley          34.0                  40.6  2006

In [5]:
#checking h_recycle
h_recycle.head()

,New Code,Code,Area,"1998/991,2","1999/001,2","2000/011,2","2001/021,2",2002/031,2003/041,2004/05,...,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,2020/21,2021/22,2022/23,2023/24
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E09000001,00AA,City of London,0.0,0,0.0,0.0,1.0,8.0,14.0,...,34.0,31.0,29.0,29.0,30.0,29.0,30.0,32.0,30.0,27.0
2,E09000002,00AB,Barking and Dagenham,3.0,3,4.0,3.0,3.0,5.0,14.0,...,23.0,19.0,25.0,25.0,24.0,25.0,27.0,31.0,33.0,33.0
3,E09000003,00AC,Barnet,9.0,8,8.0,8.0,13.0,16.0,20.0,...,38.0,37.0,37.0,37.0,35.0,32.0,29.0,30.0,27.0,29.0
4,E09000004,00AD,Bexley,20.0,18,17.0,20.0,23.0,21.0,30.0,...,54.0,52.0,53.0,52.0,54.0,54.0,50.0,43.0,44.0,46.0

In [6]:
#RUN THIS CELL TO ORGANIZE HOUSEHOLD RECYCLING DATAFRAME

#dropping blanks
hr=h_recycle.dropna().reset_index(drop=True)

#dropping columns in hr df (Area code, Code, years < 2006 and > 2020)
cols_hr = [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 13, 26, 27, 28]
hr.drop(hr.columns[cols_hr], axis=1, inplace=True)

#dropping rows in hr df (NaN's and locations that we are not interested in)
rows_hr = [0, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
hr.drop(hr.index[rows_hr], inplace=True)

#changing the column names for better merge
hr.columns = ["Area", "2006", "2007", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020"]

#making a column for years and a new column for RR/HH (recycling rate per household)
hr = hr.melt(
    id_vars=["Area"]
    ,var_name="Year"
    ,value_name="RR/HH"
)
hr = hr[["Year", "Area", "RR/HH"]]

#making years integers
hr["Year"] = hr.Year.astype("int")

#resetting index
hr = hr.reset_index(drop=True)

hr.head()

   Year                  Area  RR/HH
0  2006  Barking and Dagenham   21.0
1  2006                Barnet   29.0
2  2006                Bexley   40.0
3  2006                 Brent   22.0
4  2006               Bromley   32.0

In [7]:
#checking format for income df
income

       Year                  Area Number of Individuals  Mean £ Median £
0    2006.0        City of London                10,000  99,200   49,000
1    2006.0  Barking and Dagenham                77,000  20,600   17,600
2    2006.0                Barnet               173,000  36,700   20,400
3    2006.0                Bexley               123,000  24,600   19,600
4    2006.0                 Brent               144,000  24,600   18,200
..      ...                   ...                   ...     ...      ...
708  2020.0                 Wales             1,420,000  30,400   24,400
709  2020.0              Scotland             2,580,000  33,600   26,000
710  2020.0      Northern Ireland               783,000  31,100   24,800
711  2020.0                   NaN                   NaN     NaN      NaN
712  2020.0        United Kingdom            31,700,000  37,300   26,300

[713 rows x 5 columns]

In [8]:
#RUN THIS CELL TO ORGANIZE INCOME DATAFRAME

#cleaning rows
income = income.dropna()
income = income.set_index(income["Area"], drop = False)
income = income.drop(["City of London"
                      , "North East"
                      , "North West"
                      , "Yorkshire and The Humber"
                      , "East Midlands"
                      , "West Midlands"
                      , "East of England"
                      , "South East"
                      , "South West"
                      , "England"
                      , "Wales"
                      , "Scotland"
                      , "Northern Ireland"
                      , "United Kingdom"
                      , "London"
                      ]
                      , axis="index")
income = income.reset_index(drop = True)

#making the years integers
income["Year"] = income["Year"].astype("int")

#dropping "Number of individuals" column
income.drop(["Number of Individuals"], axis=1, inplace=True)

#renaming the Mean and Median to get rid of GBP symbol
income.rename(columns={"Mean £":"Mean","Median £":"Median"},inplace=True)

#replacing "-" with " "
income["Area"] = income["Area"].str.replace("-", " ", regex=True)

income.head()

   Year                  Area    Mean  Median
0  2006  Barking and Dagenham  20,600  17,600
1  2006                Barnet  36,700  20,400
2  2006                Bexley  24,600  19,600
3  2006                 Brent  24,600  18,200
4  2006               Bromley  32,800  23,000

In [15]:
#making the final dataframe, final adjustments and checking integrity
hr_income = pd.merge(income, hr)
final = pd.merge(hr_income, tenure)

#getting rid of commas and spaces
final["Mean"] = final["Mean"].str.replace(",","", regex=True)
final["Median"] = final["Median"].str.replace(",","", regex=True)

#renaming columns for easier use in rec_plot()
final.rename(columns = {"RR/HH":"HHRR", "Own Outright": "Own", "Buying with mortgage": "Mortgage"}, inplace=True)

#changing dtypes of values per column
final["Mean"] = final["Mean"].astype("float").astype("int")
final["Median"] = final["Median"].astype("float").astype("int")
final["HHRR"] = final["HHRR"].astype("float")
final["Own"] = final["Own"].astype("float")
final["Mortgage"] = final["Mortgage"].astype("float")
final["Year"] = final["Year"].astype("int")

#checking integrity
print("We are looking at 14 years of data and we have 32 areas, therefore we should have", 14*32, "rows.")
print("The final dataframe has", len(final),"rows and",len(final.columns),"columns.")
print("In order to check that we have no missing data, we can make the following calculation: 448 rows times 7 columns =", len(final)*len(final.columns),"values.")
print("Using Numpy.count_nonzero, we see that the final dataframe has", np.count_nonzero(final), "values.")
final.head()

We are looking at 14 years of data and we have 32 areas, therefore we should have 448 rows.
The final dataframe has 448 rows and 7 columns.
In order to check that we have no missing data, we can make the following calculation: 448 rows times 7 columns = 3136 values.
Using Numpy.count_nonzero, we see that the final dataframe has 3136 values.

   Year                  Area   Mean  Median  HHRR   Own  Mortgage
0  2006  Barking and Dagenham  20600   17600  21.0  21.6      32.4
1  2006                Barnet  36700   20400  29.0  27.7      35.0
2  2006                Bexley  24600   19600  40.0  28.5      47.2
3  2006                 Brent  24600   18200  22.0  21.3      32.3
4  2006               Bromley  32800   23000  32.0  34.0      40.6

In [10]:
#Making a function that returns the OLS, the plot and the residual plot

#making a function for the plot and residual plot
def plot(data, dv, col):
    
    #making a label for the dependent variable
    if dv == "HHRR":
        dv_lab = "Household Recycling Rate"
    else:
        print("Go to the top of the function and change the label for the dependent variable, or check the input.")

    #Making variables for the labels
    title = "Corr. between "+dv_lab+" and "
    
    if col == "Mean":
        x_lab = "Mean Income"
        title += x_lab
    
    elif col == "Median":
        x_lab = "Median Income"
        title += x_lab

    elif col == "Year":
        x_lab = col
        title += x_lab

    elif col == "Own":
        x_lab = "Own Outright"
        title += x_lab

    elif col == "Mortgage":
        x_lab = "Buying with mortgage"
        title += x_lab

    elif col == "Area":
        print("Cannot compute Area with this plot")
        
    #Plot
    y = data[dv]
    x = data[col]
    plot = (
        p9.ggplot(data
                  ,p9.aes(x = x
                          ,y = y
                         )
                 )
        +p9.theme_matplotlib()
        +p9.scale_linetype_manual(
            values = {"Correlation line" : "dotted"}
        )
        +p9.geom_point()
        +p9.geom_smooth(
            p9.aes(linetype = '"Correlation line"')
            ,method="lm"
            ,se = False
        )
        +p9.labs(
            x = x_lab
            ,y = dv_lab
            ,title = title
            ,linetype = ""
        )
    )

    #Making Residual plot
    resid_plot=sns.residplot(data, x=x, y=y, color="black");plt.xlabel(x_lab);plt.ylabel(dv_lab);plt.title("Residual Plot:\nCorr. between "+dv_lab+" and "+x_lab);plt.show()
    
    return plot
    return resid_plot

#making a function for the OLS
def rec(data, dv, col, *cols):

    #calling fstring first so we can add to it as we go
    fstring = dv + " ~ " + col

    #making *args work
    count = 0
    for i in cols:
        count += 1
        fstring += " + "+ i

    #Receipt
    model = sm.formula.ols(formula = fstring, data = data)
    model_fitted = model.fit()
    print(model_fitted.summary())

    #Making some prints for easier readability
    if data[col].dtype == int or float:
        print(
            "\nThe correlation coefficient is "+str(round(data[col].corr(data[dv]), 3))+
            ".\nThe intercept value is "+str(round(model_fitted.params.iloc[0], 3))+
            ".\nThe slope value is "+str(round(model_fitted.params.iloc[1], 3))+
            ".\nThe R-squared value is "+str(round(model_fitted.rsquared, 3))+
            ".\nThe Adjusted R-squared value is "+str(round(model_fitted.rsquared_adj, 3))+
            ".\nThe P-value is "+str(model_fitted.f_pvalue)
        )
    
    #stopping the script here if we also have the optional arguments stated
    if count == 0:
        return plot(data, dv, col)

## Coding stops here
So run all the cells above this one for the testing to work.
## Testing starts here
You can make as many cells as you want to test.

Don't change the coding above unless you receive an error.

In [ ]:
rec(final, "HHRR", "Own")

In [ ]:
rec(final, "HHRR", "Median")